
services:

  jmeter_host:
    image: jmeter-docker:5.4
    build:
      context: .
      dockerfile: Dockerfile.base
    expose:
      - "1099"
      - "50000"
    env_file:
     - .env
    command: ["/bin/bash"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    expose:
     - "4000"
     - "1099"
     - "50000"
